### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by ryancasler** [frosty5689/docker-cast-web-api#1]
When I try to run your docker image, I get the following error:

standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by frosty5689** [comment]
Where is this log from? Docker, or the container itself? That looks like
its a stacktrace from Docker itself, since its pointing to a line in a
Golang source file.

**Comment by ryancasler** [comment]
I'm not sure I understand the question.  I get the error when I try to run the image using the command you outlined in Docker Hub.  

```
docker run \
  --name cast-web-api \
  --net=host \
  -e TZ=YOUR_TIMEZONE \
  -e HOSTNAME=YOUR_HOST \
  -e PORT=YOUR_PORT \
  -p YOUR_PORT:YOUR_PORT/tcp \
  frosty5689/cast-web-api

```

**Comment by frosty5689** [comment]
What is the architecture of the Docker host you're using? If its ARM based,
then it probably wont work as I'm using x86 Alpine as base image. Also, you
need to replace the environment variable values and port valued as
appropriate for your environment.

**Comment by ryancasler** [comment]
Ah...thanks for the tip.  I will re-try with the version changed to node:8 instead.  Will report back.  Thanks!

**Comment by frosty5689** [comment]
No problem. I'm not aware of a node:8 tag for the docker images I've been
building for cast-web-api. Are you trying to run this on a Raspberry Pi? I
can look into doing multoarch builds if you'd like.

**Comment by ryancasler** [comment]
I got the build to work but now I am not able to discover any devices on the network.  So, I'm not sure what is causing that.  Probably something else I would have to do with the bridge network.  I am trying to run it on a RPi right now but I am moving my server to either a QNAP or Synology NAS in a couple months.  I'm trying to find out how many of the little apps I'm running on 3 different RPi's (one 3b+ and 2 zero w's) I can consolidate to my NAS.  I have them spread out because the system that they feed into assigns an ID by MAC address and I'm trying to figure out how to run them to get a unique MAC without being on physically different hardware.  Plus, this and one other require different versions of Node.  But it's starting to look like it's not going to be possible to move most of them.  So, I'll probably just stick with the setup I have at the moment.  Thanks for your help.
